export const famousPeople = [
    "Albert Einstein",
    "Marilyn Monroe",
    "Abraham Lincoln",
    "Leonardo da Vinci",
    "Winston Churchill",
    "William Shakespeare",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Steve Jobs",
    "Oscar Wilde",
    "Charles Darwin",
    "Vincent van Gogh",
    "Isaac Newton",
    "Pablo Picasso",
    "John F. Kennedy",
    "Mahatma Gandhi",
    "Frida Kahlo",
    "Pele",
    "Elvis Presley",
    "Amelia Earhart",
    "Marie Curie",
    "George Washington",
    "Walt Disney",
    "Napoleon Bonaparte",
    "Helen Keller",
    "Mark Twain",
    "Winston Churchill",
    "Emily Dickinson",
    "Walt Whitman",
    "Johann Wolfgang von Goethe",
    "Stephen Hawking",
    "Eleanor Roosevelt",
    "Franklin D. Roosevelt",
    "Leonardo DiCaprio",
    "Angelina Jolie",
    "Brad Pitt",
    "Madonna",
    "Michael Jackson",
    "Bruce Lee",
    "Audrey Hepburn",
    "Mother Teresa",
    "Bill Gates",
    "Malala Yousafzai",
    "Wolfgang Amadeus Mozart",
    "Ludwig van Beethoven",
    "Pablo Neruda",
    "George Orwell",
    "J.K. Rowling",
    "Leo Tolstoy",
    "Ernest Hemingway",
    "Fyodor Dostoevsky",
    "Charles Dickens",
    "Vincent Price",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Usain Bolt",
    "Muhammad Ali",
    "Serena Williams",
    "Tiger Woods",
    "Michael Jordan",
    "LeBron James",
    "Beyoncé",
    "Taylor Swift",
    "Kurt Cobain",
    "John Lennon",
    "Bob Marley",
    "Elton John",
    "Freddie Mercury",
    "Jim Morrison",
    "Jimi Hendrix",
    "Katharine Hepburn",
    "Grace Kelly",
    "Audrey Hepburn",
    "Meryl Streep",
    "Cate Blanchett",
    "Tom Hanks",
    "Johnny Depp",
    "Robert Downey Jr.",
    "Scarlett Johansson",
    "Jennifer Lawrence",
    "Bradley Cooper",
    "Daniel Day-Lewis",
    "Denzel Washington",
    "Meryl Streep",
    "Charlize Theron",
    "Harrison Ford",
    "Samuel L. Jackson",
    "Morgan Freeman",
    "Liam Neeson",
    "Julia Roberts",
    "Emma Watson",
    "Kate Winslet",
    "Julia Child",
    "Martha Stewart",
    "Jamie Oliver",
    "Gordon Ramsay",
    "Rachael Ray",
    "Anthony Bourdain",
    "Emeril Lagasse",
    "Guy Fieri",
    "Alton Brown",
];

export const quotes = [
    "Embrace the journey, not the destination.",
    "The sky is not the limit; your mind is.",
    "Dance like nobody is watching.",
    "Find the magic in the little things.",
    "The key to success is to never give up.",
    "Dream big, work hard, stay humble.",
    "Happiness is a choice, not a destination.",
    "Chase your dreams and never look back.",
    "Believe in yourself, and you can achieve anything.",
    "Life is a book; every day is a new page.",
    "The only way to fail is to never try.",
    "Change begins with you.",
    "The greatest wealth is health.",
    "Time heals all wounds.",
    "Success is not the key to happiness; happiness is the key to success.",
    "Opportunities don't happen; you create them.",
    "The harder you work, the luckier you get.",
    "Every day is a second chance.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You are the author of your own story.",
    "Your life is what you make it.",
    "The best way to predict the future is to create it.",
    "Don't count the days; make the days count.",
    "Be yourself; everyone else is already taken.",
    "The first step is the hardest.",
    "You miss 100% of the shots you don't take.",
    "What goes around, comes around.",
    "The only limit is your imagination.",
    "Kindness is free; sprinkle it everywhere.",
    "Life is short; make it sweet.",
    "Do more things that make you forget to check your phone.",
    "Success is not in what you have but who you are.",
    "Strive for progress, not perfection.",
    "A journey of a thousand miles begins with a single step.",
    "Life is a beautiful ride.",
    "The only thing standing between you and your dreams is the will to try and the belief that it is actually possible.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "In the middle of every difficulty lies opportunity.",
    "The only way to do great work is to love what you do.",
    "Don't let yesterday take up too much of today.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited; don't waste it living someone else's life.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't watch the clock; do what it does. Keep going.",
    "The greatest glory in living lies not in never falling but in rising every time we fall.",
    "Change your thoughts, and you change your world.",
    "The best revenge is massive success.",
    "Success usually comes to those who are too busy to be looking for it.",
    "A smooth sea never made a skilled sailor.",
    "The best preparation for tomorrow is doing your best today.",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "The only time to set the bar low is for limbo.",
    "Make today amazing!",
    "Don't wait for opportunity. Create it.",
    "Believe in the magic within you.",
    "The sky is not the limit; it's just the beginning.",
    "Dreams don't work unless you do.",
    "You were born to stand out, not fit in.",
    "Focus on the journey, not the destination.",
    "The only impossible journey is the one you never begin.",
    "The key to success is to focus on goals, not obstacles.",
    "The only limit is the one you set for yourself.",
    "Do something today that your future self will thank you for.",
    "Every accomplishment starts with the decision to try.",
    "A year from now, you'll wish you had started today.",
    "The secret to getting ahead is getting started.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Sometimes you win, sometimes you learn.",
    "The only way to do great work is to love what you do.",
    "Happiness is not something ready-made. It comes from your actions.",
    "The best way to predict your future is to create it.",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
    "Life is short; make it sweet.",
    "Your time is limited; don't waste it living someone else's life.",
    "To be the best, you must be able to handle the worst.",
    "The only time you should ever look back is to see how far you've come.",
    "Do more things that make you forget to check your phone.",
    "Success is not in what you have but who you are.",
    "You don't have to be great to start, but you have to start to be great.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Every day may not be good, but there is something good in every day.",
    "Hard work beats talent when talent doesn't work hard.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Dreams don't work unless you do.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only way to do great work is to love what you do.",
    "Don't let yesterday take up too much of today.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited; don't waste it living someone else's life.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't watch the clock; do what it does. Keep going.",
    "The greatest glory in living lies not in never falling but in rising every time we fall.",
    "Change your thoughts, and you change your world.",
    "The best revenge is massive success.",
    "Success usually comes to those who are too busy to be looking for it.",
    "A smooth sea never made a skilled sailor.",
    "The best preparation for tomorrow is doing your best today.",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "The only time to set the bar low is for limbo.",
    "Make today amazing!",
    "Don't wait for opportunity. Create it.",
    "Believe in the magic within you.",
    "The sky is not the limit; it's just the beginning.",
    "Dreams don't work unless you do.",
    "You were born to stand out, not fit in.",
    "Focus on the journey, not the destination.",
    "The only impossible journey is the one you never begin.",
    "The key to success is to focus on goals, not obstacles.",
    "The only limit is the one you set for yourself.",
    "Do something today that your future self will thank you for.",
    "Every accomplishment starts with the decision to try.",
    "A year from now, you'll wish you had started today.",
    "The secret to getting ahead is getting started.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Sometimes you win, sometimes you learn.",
];

const quotesWithoutPeriods = [
    "Embrace the journey, not the destination.",
    "The sky is not the limit; your mind is.",
    "Dance like nobody is watching.",
    "Find the magic in the little things.",
    "The key to success is to never give up.",
    "Dream big, work hard, stay humble.",
    "Happiness is a choice, not a destination.",
    "Chase your dreams and never look back.",
    "Believe in yourself, and you can achieve anything.",
    "Life is a book; every day is a new page.",
    "The only way to fail is to never try.",
    "Change begins with you.",
    "The greatest wealth is health.",
    "Time heals all wounds.",
    "Success is not the key to happiness; happiness is the key to success.",
    "Opportunities don't happen; you create them.",
    "The harder you work, the luckier you get.",
    "Every day is a second chance.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You are the author of your own story.",
    "Your life is what you make it.",
    "The best way to predict the future is to create it.",
    "Don't count the days; make the days count.",
    "Be yourself; everyone else is already taken.",
    "The first step is the hardest.",
    "You miss 100% of the shots you don't take.",
    "What goes around, comes around.",
    "The only limit is your imagination.",
    "Kindness is free; sprinkle it everywhere.",
    "Life is short; make it sweet.",
    "Do more things that make you forget to check your phone.",
    "Success is not in what you have but who you are.",
    "Strive for progress, not perfection.",
    "A journey of a thousand miles begins with a single step.",
    "Life is a beautiful ride.",
    "The only thing standing between you and your dreams is the will to try and the belief that it is actually possible.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "In the middle of every difficulty lies opportunity.",
    "The only way to do great work is to love what you do.",
    "Don't let yesterday take up too much of today.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited; don't waste it living someone else's life.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't watch the clock; do what it does. Keep going.",
    "The greatest glory in living lies not in never falling but in rising every time we fall.",
    "Change your thoughts, and you change your world.",
    "The best revenge is massive success.",
    "Success usually comes to those who are too busy to be looking for it.",
    "A smooth sea never made a skilled sailor.",
    "The best preparation for tomorrow is doing your best today.",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "The only time to set the bar low is for limbo.",
    "Make today amazing!",
    "Don't wait for opportunity. Create it.",
    "Believe in the magic within you.",
    "The sky is not the limit; it's just the beginning.",
    "Dreams don't work unless you do.",
    "You were born to stand out, not fit in.",
    "Focus on the journey, not the destination.",
    "The only impossible journey is the one you never begin.",
    "The key to success is to focus on goals, not obstacles.",
    "The only limit is the one you set for yourself.",
    "Do something today that your future self will thank you for.",
    "Every accomplishment starts with the decision to try.",
    "A year from now, you'll wish you had started today.",
    "The secret to getting ahead is getting started.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Sometimes you win, sometimes you learn.",
    "The only way to do great work is to love what you do.",
    "Happiness is not something ready-made. It comes from your actions.",
    "The best way to predict your future is to create it.",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
    "Life is short; make it sweet.",
    "Your time is limited; don't waste it living someone else's life.",
    "To be the best, you must be able to handle the worst.",
    "The only time you should ever look back is to see how far you've come.",
    "Do more things that make you forget to check your phone.",
    "Success is not in what you have but who you are.",
    "You don't have to be great to start, but you have to start to be great.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Every day may not be good, but there is something good in every day.",
    "Hard work beats talent when talent doesn't work hard.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Dreams don't work unless you do.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only way to do great work is to love what you do.",
    "Don't let yesterday take up too much of today.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited; don't waste it living someone else's life.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't watch the clock; do what it does. Keep going.",
    "The greatest glory in living lies not in never falling but in rising every time we fall.",
    "Change your thoughts, and you change your world.",
    "The best revenge is massive success.",
    "Success usually comes to those who are too busy to be looking for it.",
    "A smooth sea never made a skilled sailor.",
    "The best preparation for tomorrow is doing your best today.",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "The only time to set the bar low is for limbo.",
    "Make today amazing!",
    "Don't wait for opportunity. Create it.",
    "Believe in the magic within you.",
    "The sky is not the limit; it's just the beginning.",
    "Dreams don't work unless you do.",
    "You were born to stand out, not fit in.",
    "Focus on the journey, not the destination.",
    "The only impossible journey is the one you never begin.",
    "The key to success is to focus on goals, not obstacles.",
    "The only limit is the one you set for yourself.",
    "Do something today that your future self will thank you for.",
    "Every accomplishment starts with the decision to try.",
    "A year from now, you'll wish you had started today.",
    "The secret to getting ahead is getting started.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Sometimes you win, sometimes you learn.",
];